name: branch_name
description: gets a branch name changing the prefix
inputs:
  name:
    description: 'name of branch'
    required: true
  replace:
    description: 'prefix to replace'
    required: true
  with:
    description: 'replace with'
    required: true
outputs:
  branch_name:
    description: the new name
    value: ${{ steps.replace.outputs.replaced }}
runs:
  using: "composite"
  steps:
    - name: replace
      id: replace
      shell: bash
      run: |
        firstString=${{ inputs.name }}
        secondString=${{ inputs.with }}
        toreplace=${{ inputs.replace }}
        echo "replaced=${firstString/${toreplace}\//"$secondString"\/}" >> "$GITHUB_OUTPUT"