name: branch-name
description: gets a branch name replacing prefix
inputs:
  name:
    description: 'name of branch'
    required: true
  replace:
    description: 'prefix to replace'
    required: true
  with:
    description: 'replace with'
    required: true
outputs:
  branch:
    required: true
runs:
  using: "composite"
  steps:
    - name: replace
      shell: bash
      run: |
        firstString=${{ inputs.name }}
        secondString=${{ inputs.with }}
        toreplace=${{ inputs.replace }}
        echo "branch=${firstString/${toreplace}\//"$secondString"\/}" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
