name: branch-name
description: gets a branch name replacing prefix
inputs:
  name:
    description: 'name of branch'
    required: true
  replace:
    description: 'prefix to replace'
    required: true
  with:
    description: 'replace with'
    required: true
outputs:
  branch_name:
    description: the new name
runs:
  using: "composite"
  steps:
    - name: replace
      shell: bash
      run: |
        firstString=${{ inputs.name }}
        secondString=${{ inputs.with }}
        toreplace=${{ inputs.replace }}
        echo "branch_name=${firstString/${toreplace}\//"$secondString"\/}" >> "$GITHUB_OUTPUT"
        echo "branch_name=hereiam"  >> "$GITHUB_OUTPUT"
        cat $GITHUB_OUTPUT
