name: test-output
description: tests setting an output
outputs:
  theoutput:
    description: the output to test
runs:
  using: "composite"
  steps:
    - name: test
      shell: bash
      run: |
        echo theoutput=hello >> $GITHUB_OUTPUT
        echo "THE_OUPUT=tryme" >> "$GITHUB_ENV"
        cat $GITHUB_OUTPUT
        cat $GITHUB_ENV
