name: tea
description: gets tea and logs in
inputs:
  token:
    description: 'token for tea'
    required: true
runs:
  using: "composite"
  steps:
    - name: get tea
      shell: bash
      run: curl https://dl.gitea.com/tea/0.9.2/tea-0.9.2-linux-386 --output ../tea
    - name: chmod
      shell: bash
      run: chmod +x ../tea
    - name: login
      shell: bash
      run: ../tea login add -n=this --url=${{ github.server_url}} -t=${{ inputs.token}}
        