name: build-develop
run-name: from build to develop
on:
  push:
    branches:
      - 'build/**'
jobs:
  debug:
    uses: ./.github/workflows/debug.yml
  develop-branch:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/RouxAntoine/checkout/tree/v3.5.4 
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: ./.github/actions/git-prep
      - uses: ./.github/actions/branch-name
        id: develop-branch
        with:
          name: ${{ github.ref_name }}
          replace: build
          with: develop 
      - uses: gilesbradshaw/batch2yaml@master
        with:
          action: yml
          path: '.'
      - uses: ./.github/actions/i-have-changes
        id: has-changes
      - name: commit if changed
        if: ${{ steps.has-changes.outputs.changes }} == "true"
        run: |
          git add -A
          git commit -a -m "${{ github.ref_name }} -> ${{ steps.develop-branch.outputs.branch }}"
      - uses: ./.github/actions/weird-rebase
        with:
          branch: ${{ steps.develop-branch.outputs.branch }}
