name: weird-rebase
description: kind of a rebase 🤷
inputs:
  branch:
    required: true
runs:
  using: "composite"
  steps:
    - name: push changes
      shell: bash
      run: |
        if [[ $(git branch -r | grep -Fx "  origin/${{ inputs.branch }}" | wc -c) -eq 0 ]]; then
          git push origin HEAD:${{ inputs.branch }};
        else
          if [[ $(git diff origin/${{ inputs.branch }} | wc -l) -ne 0 ]]; then
            git clone ${{ github.server_url }}/${{ github.repository }} ../cloned
            git -C ../cloned fetch origin --depth=1
            git -C ../cloned checkout ${{ inputs.branch }} || git -C ../cloned checkout -b ${{ inputs.branch }}
            mv ../cloned/.git ..
            rm -rf ../cloned
            cp -r . ../cloned
            rm -rf ../cloned/.git
            mv ../.git ../cloned
            mv .git/config ../cloned/.git
            rm -r ./*
            rm -r .git
            mv ../cloned/* .
            mv ../cloned/.git .
            git add -A
            git commit -a -m "${{ github.ref_name }} -> ${{ inputs.branch }} "
            git push origin HEAD:${{ inputs.branch }}
          else
            echo 'no changes to destination branch so no push'
          fi;
        fi;
