name: test-output
description: tests setting an output
outputs:
  test_output:
    description: the output
runs:
  using: "composite"
  steps:
    - name: test
      shell: bash
      run: |
        echo test_output=hello >> $GITHUB_OUTPUT
        echo "TEST=yellow" >> "$GITHUB_ENV"
