name: develop-pr-closed
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  delete-develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: delete develop branch
        id: delete_develop_branch
        run: git push origin --delete ${{ github.head_ref }}
        continue-on-error: true
      - uses: mainmatter/continue-on-error-comment@v1
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          outcome: ${{ steps.delete_develop_branch.outcome }}
          test-id: Error code ${{ matrix.code }}
      - uses: ./.github/actions/branch-name
        id: build-branch
        with:
          name: ${{ github.head_ref}}
          replace: develop
          with: build
      - name: delete build branch
        run: git push origin --delete ${{ steps.build-branch.outputs.branch }}
  release-gitea:
    if: |
      github.event.pull_request.merged == true &&
      github.server_url != 'https://github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - id: get-latest-release
        uses: sigyl-actions/gitea-action-get-latest-release@v1.0.0
      - id: release-bumper
        uses: sigyl-actions/release-bumper@v0.0.1
        with:
          release: ${{ steps.get-latest-release.outputs.release }} 
          default-release: v0.0.1
          level: patch
      - uses: ./.github/actions/tea
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: bump release
        run: |
          version=${{ stesp.release-bumper.outputs.release }}
          ../tea r c --note="this isrelease ${version}" --tag=${version} --title=${version}  --target=${{ github.sha }};
  release-github:
    if: |
      github.event.pull_request.merged == true &&
      github.server_url == 'https://github.com'
    runs-on: ubuntu-latest
    steps:
      - id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.BOT_TOKEN }}
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(steps) }}
