name: target
on:
  pull_request_review_comment:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          fetch-depth: '1'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
