name: target
on:
  pull_request_review_comment:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
      - run: git status
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
