name: schema
run-name: test setting matix from JSON
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::[\"afile\", "\another file\"]"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
    - run: echo ${{ matrix.manifest }}
