name: schema-test
run-name: test setting matix from JSON
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: '1'
      - id: get-latest-release
        uses: sigyl-actions/gitea-action-get-latest-release@develop/no-error
        #uses: ./.github/actions/gitea-action-get-latest-release
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: sigyl-actions/xml-schema@main
        with:
          folder: '.'
          regex: ^.+\.(([aA][xX][mM][lL]))$
          xsd: ./.github/schemas/AreaModel.xsd
