name: schema-test
run-name: test setting matix from JSON
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: sigyl-actions/xml-schema@main
      with:
        folder: '.'
        regex: ^.+\.(([aA][xX][mM][lL]))$
        xsd: ./.github/schemas/AreaModel.xsd
