name: schema-test
run-name: test setting matix from JSON
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: '1'
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: sigyl-actions/xml-schema@main
        with:
          folder: '.'
          regex: ^.+\.(([aA][xX][mM][lL]))$
          xsd: ./.github/schemas/AreaModel.xsd
      - uses: sigyl-actions/xml-schema@main
        with:
          folder: './recipes'
          regex: ^.+\.(([oO][xX][mM][lL])|([uU][xX][mM][lL])|([pP][xX][mM][lL]))$
          xsd: ./.github/schemas/MasterRecipe.xsd
