name: release
run-name: from develop to build
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - id: set-matrix
      run: echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  tester:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - id: tryme
      run: echo "::set-output name=matrix::[\"afile\"]"
    - run: echo ${{ needs.job1.outputs.matrix }}
    - run: echo ${{ fromJSON(steps.tryme.outputs.matrix) }}
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
    - run: echo ${{ needs.job1.outputs.matrix }}
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}
  job3:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - project: foo
          config: Debug
        - project: bar
          config: Release
    steps:
    - run: echo ${{ matrix.project }}
    - run: echo ${{ matrix.config }}

  list-axmls:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.ls-files.outputs.files }}
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
      - id: ls-files
        uses: sigyl-actions/files-ls@v0.0.1
        with:
          folder: '.'
          regex: ^.+\.(([aA][xX][mM][lL]))$
      - run: echo "${{ steps.ls-files.outputs.files }}"
  lint:
    needs: list-axmls
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manifest: ${{ fromJSON(needs.list-axmls.outputs.matrix) }}
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: '1'
      - run: echo ${{ matrix.manifest }}
      - run: echo ${{ toJSON(matrix) }}
      - run: echo ${{ needs.list-axmls.outputs.matrix }}

  xml-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      #- name: Download schema
      #  run: wget https://apps.nextcloud.com/schema/apps/info.xsd
      - name: Validate info.xml using XML schema info.xsd
        uses: ChristophWurst/xmllint-action@v1
        with:
          xml-file: ./afile.axml
          xml-schema-file: ./AreaModel.xsd
