name: tag
run-name: from develop to build
#on:
#  release:
#    types:
#      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  