name: target
on:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - run: git status
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
