name: test
run-name: ${{ github.actor }} is testing GitHub Actions
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - id: get-latest-release
        uses: ./.github/actions/get-latest-release
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.BOT_TOKEN }}
      - id: release-bumper
        uses: ./.github/actions/release-bumper
        with:
          release: ${{ steps.get-latest-release.outputs.release }} 
          default-release: V1.0.0
          level: patch
      - id: release-bumper-1
        uses: ./.github/actions/release-bumper
        with:
          release: ${{ steps.release-bumper.outputs.release }} 
          default-release: V1.0.0
          level: patch
      - run: echo ${{ steps.release-bumper.outputs.release }}
      - run: echo ${{ steps.release-bumper-1.outputs.release }}
      - run: echo ${{ steps.get-latest-release.outputs.release }}
      - name: test
        run: |
          if [[ "${{ steps.get-latest-release.outputs.release }}" -eq "" ]]; then
            echo blank;
          else
            echo notblank;
          fi
        