name: test
run-name: ${{ github.actor }} is testing GitHub Actions
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: timeseries
        uses: ./.github/actions/get-latest-release
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.BOT_TOKEN }}
