name: test
run-name: ${{ github.actor }} is testing GitHub Actions
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - id: get-latest-release
        uses: ./.github/actions/get-latest-release
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.BOT_TOKEN }}
      - run: echo ${{ steps.get-latest-release.outputs.release }}