name: test
run-name: ${{ github.actor }} is testing GitHub Actions
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo thiswillwork >> $GITHUB_OUTPUT
        id: thisworks
      - uses: ./.github/actions/test-output
        id: test-output
      - name: json
        run: |
          echo $JSON
          echo ${{ env.TEST}}
        env:
          JSON: ${{ toJSON(steps) }}
      